name: Terraform Pipeline

on:
  push:
    branches:
      - '*'  # Run on all branches
  pull_request:
    branches:
      - '*'  # Run on all pull requests

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract Branch Name
      id: extract_branch
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}
        # Use "dev" as the default if no matching environment found
        if [[ "$BRANCH_NAME" != "dev" && "$BRANCH_NAME" != "staging" && "$BRANCH_NAME" != "prod" ]]; then
          BRANCH_NAME="dev"
        fi
        echo "Branch name: $BRANCH_NAME"
        echo "::set-output name=branch::$BRANCH_NAME"

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.0  # Specify the Terraform version to use

    - name: Terraform Init
      run: |
        cd IaC-terraform/${{ steps.extract_branch.outputs.branch }}
        terraform init

    - name: Terraform Plan
      run: |
        cd IaC-terraform/${{ steps.extract_branch.outputs.branch }}
        terraform plan -var-file=${{ steps.extract_branch.outputs.branch }}.tfvars -out=tfplan
