name: Terraform Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, staging, prod]

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0


    # Terraform Plan
    - name: Terraform Plan
      run: terraform plan -var-file="terraform-kubernetes/config/${{ matrix.environment }}/${{ matrix.environment }}.tfvars" -out=tfplan



